# Generated by Django 5.1.6 on 2025-04-24 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_historial', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnostico', models.TextField(null=True)),
                ('sintoma', models.CharField(max_length=200, null=True)),
                ('observacion', models.TextField(null=True)),
            ],
        ),
    ]
