# Generated by Django 5.1.6 on 2025-04-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial_clinico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinicomodel',
            name='fk_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.pacientemodel'),
        ),
    ]
