# Generated by Django 5.1.6 on 2025-06-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinicomodel',
            name='reserva_uuid',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
