# Generated by Django 5.1.6 on 2025-04-24 18:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default='00:00:00')),
                ('hora_termino', models.TimeField(default='00:00:00')),
                ('especialidad', models.CharField(max_length=200, null=True)),
                ('nombre_doctor', models.CharField(max_length=250, null=True)),
                ('tipo_pago', models.CharField(max_length=250, null=True)),
                ('id_doctor', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('reserva_uuid', models.CharField(max_length=250, null=True)),
                ('nombre_clinica', models.CharField(max_length=250, null=True)),
                ('comuna_clinica', models.CharField(max_length=250, null=True)),
                ('direccion_clinica', models.CharField(max_length=250, null=True)),
                ('reserva_cerrada', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
