# Generated by Django 5.1.6 on 2025-03-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('especialidad', models.CharField(max_length=200, null=True)),
                ('nombre_doctor', models.CharField(max_length=250, null=True)),
                ('tipo_pago', models.CharField(max_length=250, null=True)),
                ('usuario_uuid', models.CharField(max_length=250, null=True)),
                ('reserva_uuid', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
