# Generated by Django 5.1.6 on 2025-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservamodel',
            name='id_doctor',
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='usuario_creacion_reserva',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
