# Generated by Django 5.1.6 on 2025-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.IntegerField(null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('credito_uuid', models.CharField(max_length=255, null=True)),
                ('cant_cuotas', models.IntegerField(null=True)),
                ('monto_total', models.IntegerField(null=True)),
                ('monto_cuotas', models.IntegerField(null=True)),
            ],
        ),
    ]
