# Generated by Django 5.1.6 on 2025-02-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
