# Generated by Django 5.1.6 on 2025-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=250, null=True)),
                ('segundo_nombre', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('rut', models.TextField(max_length=250, null=True)),
                ('fono', models.TextField(max_length=250, null=True)),
                ('paciente_uuid', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
