# Generated by Django 5.1.6 on 2025-04-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientemodel',
            name='email',
        ),
    ]
