# Generated by Django 5.1.6 on 2025-03-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=250, null=True)),
                ('ap_paterno', models.TextField(max_length=100, null=True)),
                ('ap_materno', models.TextField(max_length=100, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('consulta', models.TextField(null=True)),
            ],
        ),
    ]
