# Generated by Django 5.1.6 on 2025-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='consulta',
            field=models.TextField(null=True),
        ),
    ]
