# Generated by Django 5.1.6 on 2025-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comuna_clinica', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunaclinicamodel',
            name='clinica_doctor',
            field=models.ManyToManyField(to='doctor.doctormodel'),
        ),
    ]
