# Generated by Django 5.1.6 on 2025-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuna_clinica', '0002_initial'),
        ('secretaria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunaclinicamodel',
            name='clinica_secretaria',
            field=models.ManyToManyField(to='secretaria.secretariamodel'),
        ),
    ]
