# Generated by Django 5.1.6 on 2025-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customersusers_usuario_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersusers',
            name='password',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
