# Generated by Django 5.1.6 on 2025-03-17 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debito', '0001_initial'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitomodel',
            name='fk_reserva',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.reservamodel'),
        ),
    ]
