# Generated by Django 5.1.6 on 2025-04-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_remove_secretariamodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariamodel',
            name='ap_materno',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='secretariamodel',
            name='ap_paterno',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
