# Generated by Django 5.1.6 on 2025-06-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuna_clinica', '0003_comunaclinicamodel_clinica_secretaria'),
        ('secretaria', '0004_secretariamodel_ap_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariamodel',
            name='secretaria_clinica',
            field=models.ManyToManyField(to='comuna_clinica.comunaclinicamodel'),
        ),
    ]
